#!/usr/bin/env python3
"""Compare benchmark runs: every recipe side by side, next to the published reference numbers.

    python3 bench/compare.py                 # newest run of each recipe/label, writes results/LEADERBOARD.md
    python3 bench/compare.py --all           # every run, oldest first (to see a change over time)
    python3 bench/compare.py --recipe glm-5.3-flash --all
    python3 bench/compare.py --csv > runs.csv

Standard library only.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STANDARD = ["code-sampled", "chat-sampled", "code-greedy", "chat-greedy"]
LONG = ["code-greedy-512", "prose-greedy-512", "json-greedy-512", "prose-sampled-512"]


def load_runs(recipe: str | None) -> list[dict]:
    runs = []
    for f in sorted((ROOT / "results").glob("*/*.json")):
        try:
            r = json.loads(f.read_text())
        except ValueError:
            continue
        if r.get("schema") != 1 or (recipe and r["recipe"] != recipe):
            continue
        r["_file"] = str(f.relative_to(ROOT))
        runs.append(r)
    runs.sort(key=lambda r: r["started_utc"])
    return runs


def cell(run: dict, suite: str, name: str) -> dict | None:
    return next((c for c in run["cells"] if c["suite"] == suite and c["cell"] == name), None)


def tps(run: dict, suite: str, name: str) -> str:
    c = cell(run, suite, name)
    if not c or c.get("decode_tps_median") is None:
        return "–"
    flag = "*" if c.get("slow_runs_flagged") and c.get("greedy") else ""   # sampled seeds differ by design
    return f"{c['decode_tps_median']:.1f}{flag}"


def prefill(run: dict) -> str:
    cells = [c for c in run["cells"] if c["suite"] == "prefill"]
    return " / ".join(f"{c['prefill_tps']:.0f}" for c in cells) if cells else "–"


def exact(run: dict) -> str:
    c = cell(run, "exactness", "drafted-vs-serial")
    return f"{c['passed']}/{c['total']}" if c else "–"


def platform(run: dict) -> str:
    return run["meta"].get("platform", "?")


def row_name(run: dict) -> str:
    return run["recipe"] + (f" [{run['label']}]" if run.get("label") else "")


def render(runs: list[dict]) -> str:
    out = ["# Leaderboard", "",
           "Generated by `python3 bench/compare.py` from `results/*/*.json`. Decode tok/s, one stream, medians.",
           "`*` = a greedy cell whose runs still disagreed by more than 15% after a re-measure (GB10 page migration);",
           "run it again before trusting it.", "",
           "## Standard cells (comparable with the published numbers below)", "",
           "| Recipe | Platform | Code, sampled | Chat, sampled | Code, greedy | Chat, greedy | Exact | Date |",
           "| --- | --- | ---: | ---: | ---: | ---: | :---: | --- |"]
    has = lambda r, suite: any(c["suite"] == suite for c in r["cells"])      # noqa: E731
    for r in (r for r in runs if has(r, "standard")):
        out.append(f"| {row_name(r)} | {platform(r)} | " + " | ".join(tps(r, "standard", c) for c in STANDARD)
                   + f" | {exact(r)} | {r['started_utc'][:16].replace('T', ' ')} |")
    out += ["", "## Real work: 512-token replies and cold prefill", "",
            "| Recipe | Platform | Code, greedy | Prose, greedy | JSON, greedy | Prose, sampled | Prefill tok/s (per size) | Prefill sizes |",
            "| --- | --- | ---: | ---: | ---: | ---: | --- | --- |"]
    for r in (r for r in runs if has(r, "long") or has(r, "prefill")):
        sizes = " / ".join(str(c["prompt_tokens"]) for c in r["cells"] if c["suite"] == "prefill") or "–"
        out.append(f"| {row_name(r)} | {platform(r)} | " + " | ".join(tps(r, "long", c) for c in LONG)
                   + f" | {prefill(r)} | {sizes} |")
    ctx = [r for r in runs if any(c["suite"] == "context" for c in r["cells"])]
    if ctx:
        out += ["", "## Long context (coding agent: cold codebase prompt, then a follow-up turn)", "",
                "| Recipe | Platform | Prompt tokens | Prefill tok/s | TTFT | Decode tok/s at depth | Needle | Follow-up TTFT |",
                "| --- | --- | ---: | ---: | ---: | ---: | :---: | ---: |"]
        for r in ctx:
            for c in (c for c in r["cells"] if c["suite"] == "context"):
                out.append(f"| {row_name(r)} | {platform(r)} | {c['prompt_tokens']:,} | {c['prefill_tps']:.0f} | "
                           f"{c['ttft_s']:.1f} s | {c['decode_tps_median'] or 0:.1f} | "
                           f"{'yes' if c['needle_found'] else 'NO'} | {c['followup_ttft_s']:.1f} s |")
    conc = [r for r in runs if any(c["suite"] == "concurrency" for c in r["cells"])]
    if conc:
        out += ["", "## Concurrency", "", "| Recipe | Streams | Per stream | Aggregate |", "| --- | ---: | ---: | ---: |"]
        for r in conc:
            for c in (c for c in r["cells"] if c["suite"] == "concurrency"):
                out.append(f"| {row_name(r)} | {c['streams']} | {c['decode_tps_median']:.1f} | {c['aggregate_tps']:.1f} |")
    ref = json.loads((ROOT / "bench" / "reference.json").read_text())
    out += ["", "## Published reference numbers", "", ref["about"], "",
            "| Recipe | Platform | Engine | Code, sampled | Chat, sampled | Code, greedy | Chat, greedy |",
            "| --- | --- | --- | ---: | ---: | ---: | ---: |"]
    for r in ref["rows"]:
        cells = " | ".join(f"{x:.1f}" for x in r["standard"]) if r.get("standard") else f"{r.get('other', '')} | | |"
        out.append(f"| {r['recipe']} | {r['platform']} | {r['engine']} | {cells} |")
    return "\n".join(out) + "\n"


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--all", action="store_true", help="every run instead of the newest per recipe and label")
    p.add_argument("--recipe")
    p.add_argument("--csv", action="store_true", help="one line per cell, to stdout")
    p.add_argument("--no-write", action="store_true", help="don't write results/LEADERBOARD.md")
    a = p.parse_args()
    runs = load_runs(a.recipe)
    if not a.all:
        newest = {}
        for r in runs:
            newest[(r["recipe"], r.get("label", ""), platform(r))] = r
        runs = sorted(newest.values(), key=lambda r: (r["recipe"], r.get("label", "")))
    if a.csv:
        w = csv.writer(sys.stdout)
        w.writerow(["recipe", "label", "platform", "started_utc", "suite", "cell", "decode_tps_median",
                    "ttft_s_median", "prefill_tps", "file"])
        for r in runs:
            for c in r["cells"]:
                w.writerow([r["recipe"], r.get("label", ""), platform(r), r["started_utc"], c["suite"], c["cell"],
                            c.get("decode_tps_median", ""), c.get("ttft_s_median", ""), c.get("prefill_tps", ""),
                            r["_file"]])
        return
    md = render(runs)
    print(md)
    if not a.no_write and not a.recipe and not a.all:
        (ROOT / "results" / "LEADERBOARD.md").write_text(md)
        print("wrote results/LEADERBOARD.md", file=sys.stderr)


if __name__ == "__main__":
    main()
